# Generated by Django 5.2.5 on 2025-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_author_course_duration_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.CharField(blank=True, default='Unknown', help_text="Enter author's name", max_length=100),
        ),
    ]
